<a href="https://colab.research.google.com/github/gramelon2003/Python_ptdl/blob/master/axis_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Bài 1: 
numpy.apply_along_axis(func1d, axis, arr, *args, **kwargs)
func1d: Hàm chấp nhận mảng 1 chiều
axis: Trục mà mảng bị cắt
arr: Mảng nhập vào
agrs: Đối số bổ sung hàm func1d
kwargs: Đối số được đặt tên bổ sung của hàm func1d

B2

In [16]:
import numpy as np
a = np.random.randint(50, size=(15, 17))
print(a)

[[13 28 41  6 34 18 16  2 31 16 33 17 14  9 38 26 17]
 [47 27  9 40 13 18 48 43 16 15 39  2 29 42 10 13  9]
 [20 16 41 24 35 45 28  7 26 27 34  6  4 22 27 49 38]
 [44 36 48 20  7  7  9 36 49 44 48 24 21 17 11  1 43]
 [15 25 27  7 48 22 28 38  4  0 40  7 41  0 26 32  1]
 [11 30 10 18 36 25  0 25 19  6 20 41 34 43 44 22 48]
 [15  5 17 43 20 13  8 38 48 45  3 25 19 35 30  2  9]
 [10 38 42 22 31 32  1 42 29  8  0 18 20  8 47 31  8]
 [ 7  6 49 43  2 21 49 41 34 18 30 49 14 30 20 11 27]
 [21 33 18 31  8 42 45 15 22 34 14 25 27 21 41 11 46]
 [31 15 34  7 16 48  3  6  5 18 43 31 35 43 39 46 19]
 [19 25 30 30  0 12 46 18  7 18 39 37 17 39 24 32  9]
 [ 5 19 19 18 18 43 38  8 32 13 13 18 42 37 41 43  1]
 [48 38  7 35 18 19 40 34 16 34 19 19  8 32 16  1 30]
 [17 35  8  6 14 35 17 36 49 16 15 48 26 33 13 45 16]]


Bài 3

In [28]:
import numpy as np
b = np.apply_along_axis(max, 1, a)
print(b)

[41 48 49 49 48 48 48 47 49 46 48 46 43 48 49]


Bài 4

In [29]:
import numpy as np
c = np.apply_along_axis(max, 0, a)
print(c)

[48 38 49 43 48 48 49 43 49 45 48 49 42 43 47 49 48]


Bài 5

In [31]:
import numpy as np
d = np.apply_along_axis(sum, 0, a)
print(d)

[323 376 400 350 300 400 376 389 387 312 390 367 351 411 427 365 321]


Bài 6

In [46]:
import numpy as np
def tinh_tong2(a): 
    s = 0
    for i in range(0,len(a)): 
        if i % 2 != 0: 
            s += a[i]
    return s
e = np.apply_along_axis(tinh_tong2, 0, a)
print(e)
f = np.apply_along_axis(tinh_tong2, 1, a)
print(f)

[200 227 164 196 113 155 189 213 158 159 179 166 156 202 193 111 193]
[122 200 196 185 131 210 206 199 219 212 214 211 199 212 254]
