<a href="https://colab.research.google.com/github/gramelon2003/Python_ptdl/blob/master/bai_tap_sinh_mau_ngau_nhien.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Sử dụng thư viện Numpy

1. Sinh mẫu ngẫu nhiên bằng hàm arange trong khoảng [-15, 27] với khoảng cách là 0.7 và in kết quả ra màn hình

In [3]:
import numpy as np
a = np.arange(-15, 27, 0.7)
a

array([-15. , -14.3, -13.6, -12.9, -12.2, -11.5, -10.8, -10.1,  -9.4,
        -8.7,  -8. ,  -7.3,  -6.6,  -5.9,  -5.2,  -4.5,  -3.8,  -3.1,
        -2.4,  -1.7,  -1. ,  -0.3,   0.4,   1.1,   1.8,   2.5,   3.2,
         3.9,   4.6,   5.3,   6. ,   6.7,   7.4,   8.1,   8.8,   9.5,
        10.2,  10.9,  11.6,  12.3,  13. ,  13.7,  14.4,  15.1,  15.8,
        16.5,  17.2,  17.9,  18.6,  19.3,  20. ,  20.7,  21.4,  22.1,
        22.8,  23.5,  24.2,  24.9,  25.6,  26.3,  27. ])

2. Sinh mẫu ngẫu nhiên theo phân phối chuẩn với mean = 2.7 std = 1.2 và size = 40
In kết quả ra màn hình

In [4]:
b = np.random.normal(2.7, 1.2, size = 40)
b

array([ 4.77844977,  1.87845151,  4.12593435,  3.079036  ,  5.436459  ,
        1.62708009,  1.93385602,  1.35376952,  1.46981838,  1.02040825,
        4.11500451,  1.8024862 ,  3.64883621,  2.56262234,  3.65477477,
        1.67985289,  1.86920913,  2.74024271,  1.12520627,  2.59545594,
        3.0914614 ,  1.66188512,  3.28561991,  2.68785576,  0.81030562,
        2.03796282,  3.96249503,  0.99901484,  2.16185512,  1.99867746,
        3.2840905 ,  4.89536491,  3.8397485 ,  0.62662321,  1.96931862,
       -0.31745238,  1.41459779,  4.20220097,  3.06680994,  1.77903923])

3. Sinh mẫu ngẫu nhiên từ vector ['Viet Nam', 'Britain', 'France', 'Russia', 'Singapore'] 

với kích thước là 17 theo phân phối chuẩn

In [6]:
c = ['Viet Nam', 'Britain', 'France', 'Russia', 'Singapore']
d = np.random.choice(c, 17)
d

array(['Viet Nam', 'Britain', 'Singapore', 'Russia', 'France', 'Britain',
       'Singapore', 'Russia', 'Russia', 'Viet Nam', 'France', 'Singapore',
       'Viet Nam', 'Viet Nam', 'Britain', 'France', 'Russia'], dtype='<U9')

4. Sinh mẫu ngẫu nhiên ở câu 3 nhưng không theo phân phối chuẩn mà theo 1 vector đặc tả giá trị xác suất do bạn chọn

In [9]:
e = np.random.choice(c, 17, p = [0.1, 0.4, 0.2, 0.15, 0.15])
e

array(['France', 'Britain', 'Russia', 'France', 'Britain', 'Britain',
       'Russia', 'Britain', 'Britain', 'Singapore', 'Singapore', 'Russia',
       'France', 'Britain', 'Singapore', 'Russia', 'Britain'], dtype='<U9')

Sử dụng thư việc scipy.stats để sinh mẫu ngẫu nhiên

1. Sinh mẫu ngẫu nhiên theo phân phối chuẩn với mean = 12.7, std = 2.6 và size = 30. In kết quả ra màn hình

In [12]:
from scipy import stats

In [13]:
f = stats.norm.rvs(12.7, 2.6, size = 30)

2. Hãy sinh một mẫu ngẫu nhiên theo phân phối Poisson

In [15]:
g = stats.poisson.rvs(45, 20, size=1000)
print(g[:10])

[58 63 72 65 67 71 62 74 55 57]
