<a href="https://colab.research.google.com/github/gramelon2003/Python_ptdl/blob/master/Numpy_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Bài 1

In [ ]:
import numpy as np
a = [5, 7, 14]
b = np.array(a)
print(b)

[ 5  7 14]


Bài 2

In [ ]:
import numpy as np
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
b = np.array(a)
print(b)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


Bài 3

In [ ]:
import numpy as np
n = int(input("nhap so n tu ban phim: "))
a = np.random.randint(0, 20, n)
print(a)

nhap so n tu ban phim: 7
[ 4 15  6  4 18  4 10]


Bài 4

In [ ]:
import numpy as np
a = np.array([7, -5, 8])
m = np.linalg.norm(a)
print(m)

11.74734012447073


Bài 5

Bài 6

In [ ]:
import numpy as np
n = int(input("nhap so n tu ban phim: "))
a = np.random.randint(0, 20, n)
b = np.random.randint(0, 20, n)
c = np.inner(a, b)
print(c)

nhap so n tu ban phim: 4
166


Bài 7

In [ ]:
import numpy as np
n = int(input("nhap so n tu ban phim: "))
a = np.random.randint(0, 20, n)
b = np.random.randint(0, 20, n)
c = np.cross(a, b)
print(c)

nhap so n tu ban phim: 3
[ 129 -115 -234]


Bài 8

In [ ]:
import numpy as np
a = np.random.randint(0, 20, 3)
print(a)
b = np.transpose(a)
print(b)

[ 7  6 14]
[ 7  6 14]


Bài 9

In [ ]:
import numpy as np
a = [1, 2, 3, 4, 5]
b = [[1], [2], [3], [4], [5]]
print(a)
print(b)
c = np.array(a)
d = np.array(b)
print(c)
print(d)
e = np.transpose(a)
f = np.transpose(b)
print(e)
print(f)

[1, 2, 3, 4, 5]
[[1], [2], [3], [4], [5]]
[1 2 3 4 5]
[[1]
 [2]
 [3]
 [4]
 [5]]
[1 2 3 4 5]
[[1 2 3 4 5]]


Bài 10

In [ ]:
import random
import numpy as np
n = int(input("nhap so n tu ban phim: "))
a = np.random.randint(0, 20, n)
b = np.random.randint(0, 20, n)
c = random.randint(0, 10)
d = a*c
e = np.add(a, b)
print(a)
print(b)
print(c)
print(d)
print(e)

nhap so n tu ban phim: 3
[15 17  7]
[17 12 17]
6
[ 90 102  42]
[32 29 24]
