<a href="https://colab.research.google.com/github/gramelon2003/Python_ptdl/blob/master/numpy4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Bài 1

In [ ]:
import numpy as np
a = np.arange(-3, 4, 1, dtype=int)
a1 = np.transpose(a)
b = np.linspace(0, 6, 7)
b1 = np.transpose(b)
c = np.logspace(1.0, 7.0, num=7, base = 2)
c1 = np.transpose(c)
d = np.random.rand(1,7)
d1 = np.transpose(d)
print(a)
print(a.ndim, a1.ndim, a.shape, a1.shape)
print(b)
print(b.ndim, b1.ndim, b.shape, b1.shape)
print(c)
print(c.ndim, c1.ndim, c.shape, c1.shape)
print(d)
print(d.ndim, d1.ndim, d.shape, d1.shape)

[-3 -2 -1  0  1  2  3]
1 1 (7,) (7,)
[0. 1. 2. 3. 4. 5. 6.]
1 1 (7,) (7,)
[  2.   4.   8.  16.  32.  64. 128.]
1 1 (7,) (7,)
[[0.15909327 0.61054723 0.27150183 0.80741608 0.69823313 0.08734429
  0.96046602]]
2 2 (1, 7) (7, 1)


Bài 2

In [ ]:
import numpy as np
a = np.arange(0, 70, 1)
a.shape = (10,7)
a1 = np.transpose(a)
b = np.linspace(0, 69, 70)
b.shape = (10,7)
b1 = np.transpose(b)
c = np.logspace(0, 10, num=70, base = 2)
c.shape = (10,7)
c1 = np.transpose(c)
d = np.random.rand(1, 70)
d.shape = (10,7)
d1 = np.transpose(d)
print(a)
print(a.ndim, a1.ndim, a.shape, a1.shape)
print(b)
print(b.ndim, b1.ndim, b.shape, b1.shape)
print(c)
print(c.ndim, c1.ndim, c.shape, c1.shape)
print(d)
print(d.ndim, d1.ndim, d.shape, d1.shape)

[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34]
 [35 36 37 38 39 40 41]
 [42 43 44 45 46 47 48]
 [49 50 51 52 53 54 55]
 [56 57 58 59 60 61 62]
 [63 64 65 66 67 68 69]]
2 2 (10, 7) (7, 10)
[[ 0.  1.  2.  3.  4.  5.  6.]
 [ 7.  8.  9. 10. 11. 12. 13.]
 [14. 15. 16. 17. 18. 19. 20.]
 [21. 22. 23. 24. 25. 26. 27.]
 [28. 29. 30. 31. 32. 33. 34.]
 [35. 36. 37. 38. 39. 40. 41.]
 [42. 43. 44. 45. 46. 47. 48.]
 [49. 50. 51. 52. 53. 54. 55.]
 [56. 57. 58. 59. 60. 61. 62.]
 [63. 64. 65. 66. 67. 68. 69.]]
2 2 (10, 7) (7, 10)
[[1.00000000e+00 1.10567512e+00 1.22251746e+00 1.35170714e+00
  1.49454895e+00 1.65248558e+00 1.82711218e+00]
 [2.02019248e+00 2.23367655e+00 2.46972058e+00 2.73070859e+00
  3.01927653e+00 3.33833893e+00 3.69111829e+00]
 [4.08117764e+00 4.51245656e+00 4.98931093e+00 5.51655694e+00
  6.09951974e+00 6.74408719e+00 7.45676939e+00]
 [8.24476436e+00 9.11603079e+00 1.00793684e+01 1.11445068e+01
  1.23222039e+01

Bài 3

In [ ]:
import numpy as np
a = np.arange(0, 70, 1)
a.shape = (10,7)
a1 = a.flatten()
a2 = a1.reshape(10,7)
b = np.linspace(0, 69, 70)
b.shape = (10,7)
b1 = b.flatten()
b2 = b1.reshape(10,7)
c = np.logspace(0, 10, num=70, base = 2)
c.shape = (10,7)
c1 = c.flatten()
c2 = c1.reshape(10,7)
d = np.random.rand(1, 70)
d.shape = (10,7)
d1 = d.flatten()
d2 = d1.reshape(10,7)
print(a)
print(a1)
print(a2)
print(b)
print(b1)
print(b2)
print(c)
print(c1)
print(c2)
print(d)
print(d1)
print(d2)

[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34]
 [35 36 37 38 39 40 41]
 [42 43 44 45 46 47 48]
 [49 50 51 52 53 54 55]
 [56 57 58 59 60 61 62]
 [63 64 65 66 67 68 69]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69]
[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34]
 [35 36 37 38 39 40 41]
 [42 43 44 45 46 47 48]
 [49 50 51 52 53 54 55]
 [56 57 58 59 60 61 62]
 [63 64 65 66 67 68 69]]
[[ 0.  1.  2.  3.  4.  5.  6.]
 [ 7.  8.  9. 10. 11. 12. 13.]
 [14. 15. 16. 17. 18. 19. 20.]
 [21. 22. 23. 24. 25. 26. 27.]
 [28. 29. 30. 31. 32. 33. 34.]
 [35. 36. 37. 38. 39. 40. 41.]
 [42. 43. 44. 45. 46. 47. 48.]
 [49. 50. 51. 52. 53. 54. 55.]
 [56. 57. 58. 59. 60. 61. 62.]
 [63. 64. 65. 66. 67. 68.

Bài 4

In [ ]:
import numpy as np
a = np.logspace(0, 149, num=150)
a.shape = (10,15)
a3 = a[3,:]
a5 = a[:,5]
print(a)
print(a3)
print(a5)

[[1.e+000 1.e+001 1.e+002 1.e+003 1.e+004 1.e+005 1.e+006 1.e+007 1.e+008
  1.e+009 1.e+010 1.e+011 1.e+012 1.e+013 1.e+014]
 [1.e+015 1.e+016 1.e+017 1.e+018 1.e+019 1.e+020 1.e+021 1.e+022 1.e+023
  1.e+024 1.e+025 1.e+026 1.e+027 1.e+028 1.e+029]
 [1.e+030 1.e+031 1.e+032 1.e+033 1.e+034 1.e+035 1.e+036 1.e+037 1.e+038
  1.e+039 1.e+040 1.e+041 1.e+042 1.e+043 1.e+044]
 [1.e+045 1.e+046 1.e+047 1.e+048 1.e+049 1.e+050 1.e+051 1.e+052 1.e+053
  1.e+054 1.e+055 1.e+056 1.e+057 1.e+058 1.e+059]
 [1.e+060 1.e+061 1.e+062 1.e+063 1.e+064 1.e+065 1.e+066 1.e+067 1.e+068
  1.e+069 1.e+070 1.e+071 1.e+072 1.e+073 1.e+074]
 [1.e+075 1.e+076 1.e+077 1.e+078 1.e+079 1.e+080 1.e+081 1.e+082 1.e+083
  1.e+084 1.e+085 1.e+086 1.e+087 1.e+088 1.e+089]
 [1.e+090 1.e+091 1.e+092 1.e+093 1.e+094 1.e+095 1.e+096 1.e+097 1.e+098
  1.e+099 1.e+100 1.e+101 1.e+102 1.e+103 1.e+104]
 [1.e+105 1.e+106 1.e+107 1.e+108 1.e+109 1.e+110 1.e+111 1.e+112 1.e+113
  1.e+114 1.e+115 1.e+116 1.e+117 1.e+118 1.e+119]


Bài 5

5.1

In [8]:
import numpy as np
def tinh_tb(a): 
    s = 0
    for i in range(0,len(a)): 
        s += a[i]
    tb = s/len(a)
    return tb
a = np.random.randint(0, 50, size = (15,10))
b = np.apply_along_axis(tinh_tb, 0, a)
c = np.apply_along_axis(tinh_tb, 1, a)
print(a)
print("áp dụng trên cột", b)
print("áp dụng trên hàng", c)

[[33 32  5 40 21  6 30 39 43 13]
 [16  0 28 46 34 28 30 36 48 21]
 [15 17 25 26 15 10 17 26  4 41]
 [10 33  4 26 45 31 17 42 20 23]
 [36  4 11 45 29 32  0 29 36 32]
 [30 18 13  5 20  9  4 27 18  5]
 [40  7  0 36 47 26 17 48 44 32]
 [41 15 14 47 48 45 10 20 18  7]
 [25 35  8 26 25 29 46 33  1 17]
 [ 5 15 36 33 49  4 17  5 49 21]
 [28 22 24 20 34 48 43 34 27 24]
 [20 21  1 12 23 41 38 30 23 47]
 [40 47 26 17 45 39  1 35 27 27]
 [48 36  8 13 16 34 41 16 27 22]
 [34 38  0 12  7  7 17 19 40 22]]
áp dụng trên cột [28.06666667 22.66666667 13.53333333 26.93333333 30.53333333 25.93333333
 21.86666667 29.26666667 28.33333333 23.6       ]
áp dụng trên hàng [26.2 28.7 19.6 25.1 25.4 14.9 29.7 26.5 24.5 23.4 30.4 25.6 30.4 26.1
 19.6]


5.2

In [9]:
import numpy as np
import statistics as sta
b = np.apply_along_axis(sta.median, 0, a)
c = np.apply_along_axis(sta.median, 1, a)
print(a)
print("áp dụng trên cột", b)
print("áp dụng trên hàng", c)

[[33 32  5 40 21  6 30 39 43 13]
 [16  0 28 46 34 28 30 36 48 21]
 [15 17 25 26 15 10 17 26  4 41]
 [10 33  4 26 45 31 17 42 20 23]
 [36  4 11 45 29 32  0 29 36 32]
 [30 18 13  5 20  9  4 27 18  5]
 [40  7  0 36 47 26 17 48 44 32]
 [41 15 14 47 48 45 10 20 18  7]
 [25 35  8 26 25 29 46 33  1 17]
 [ 5 15 36 33 49  4 17  5 49 21]
 [28 22 24 20 34 48 43 34 27 24]
 [20 21  1 12 23 41 38 30 23 47]
 [40 47 26 17 45 39  1 35 27 27]
 [48 36  8 13 16 34 41 16 27 22]
 [34 38  0 12  7  7 17 19 40 22]]
áp dụng trên cột [30 21 11 26 29 29 17 30 27 22]
áp dụng trên hàng [31.  29.  17.  24.5 30.5 15.5 34.  19.  25.5 19.  27.5 23.  31.  24.5
 18. ]


5.3

In [10]:
import numpy as np
import statistics as sta
b = np.apply_along_axis(sta.mean, 0, a)
c = np.apply_along_axis(sta.mean, 1, a)
print(a)
print("áp dụng trên cột", b)
print("áp dụng trên hàng", c)

[[33 32  5 40 21  6 30 39 43 13]
 [16  0 28 46 34 28 30 36 48 21]
 [15 17 25 26 15 10 17 26  4 41]
 [10 33  4 26 45 31 17 42 20 23]
 [36  4 11 45 29 32  0 29 36 32]
 [30 18 13  5 20  9  4 27 18  5]
 [40  7  0 36 47 26 17 48 44 32]
 [41 15 14 47 48 45 10 20 18  7]
 [25 35  8 26 25 29 46 33  1 17]
 [ 5 15 36 33 49  4 17  5 49 21]
 [28 22 24 20 34 48 43 34 27 24]
 [20 21  1 12 23 41 38 30 23 47]
 [40 47 26 17 45 39  1 35 27 27]
 [48 36  8 13 16 34 41 16 27 22]
 [34 38  0 12  7  7 17 19 40 22]]
áp dụng trên cột [28 22 13 26 30 25 21 29 28 23]
áp dụng trên hàng [26 28 19 25 25 14 29 26 24 23 30 25 30 26 19]


5.4

In [11]:
import numpy as np
b = np.apply_along_axis(np.var, 0, a)
c = np.apply_along_axis(np.var, 1, a)
print(a)
print("áp dụng trên cột", b)
print("áp dụng trên hàng", c)

[[33 32  5 40 21  6 30 39 43 13]
 [16  0 28 46 34 28 30 36 48 21]
 [15 17 25 26 15 10 17 26  4 41]
 [10 33  4 26 45 31 17 42 20 23]
 [36  4 11 45 29 32  0 29 36 32]
 [30 18 13  5 20  9  4 27 18  5]
 [40  7  0 36 47 26 17 48 44 32]
 [41 15 14 47 48 45 10 20 18  7]
 [25 35  8 26 25 29 46 33  1 17]
 [ 5 15 36 33 49  4 17  5 49 21]
 [28 22 24 20 34 48 43 34 27 24]
 [20 21  1 12 23 41 38 30 23 47]
 [40 47 26 17 45 39  1 35 27 27]
 [48 36  8 13 16 34 41 16 27 22]
 [34 38  0 12  7  7 17 19 40 22]]
áp dụng trên cột [148.32888889 175.55555556 124.38222222 176.86222222 177.18222222
 211.12888889 218.64888889 112.99555556 208.35555556 119.97333333]
áp dụng trên hàng [178.96 180.01  96.04 154.89 203.24  77.29 256.21 249.05 154.85 273.24
  77.24 172.44 176.24 158.29 173.44]


5.5

In [12]:
import numpy as np
b = np.apply_along_axis(np.std, 0, a)
c = np.apply_along_axis(np.std, 1, a)
print(a)
print("áp dụng trên cột", b)
print("áp dụng trên hàng", c)

[[33 32  5 40 21  6 30 39 43 13]
 [16  0 28 46 34 28 30 36 48 21]
 [15 17 25 26 15 10 17 26  4 41]
 [10 33  4 26 45 31 17 42 20 23]
 [36  4 11 45 29 32  0 29 36 32]
 [30 18 13  5 20  9  4 27 18  5]
 [40  7  0 36 47 26 17 48 44 32]
 [41 15 14 47 48 45 10 20 18  7]
 [25 35  8 26 25 29 46 33  1 17]
 [ 5 15 36 33 49  4 17  5 49 21]
 [28 22 24 20 34 48 43 34 27 24]
 [20 21  1 12 23 41 38 30 23 47]
 [40 47 26 17 45 39  1 35 27 27]
 [48 36  8 13 16 34 41 16 27 22]
 [34 38  0 12  7  7 17 19 40 22]]
áp dụng trên cột [12.17903481 13.24973794 11.15267781 13.29895568 13.31098126 14.53027491
 14.78678088 10.62993676 14.43452651 10.95323392]
áp dụng trên hàng [13.37759321 13.41678054  9.8        12.44548111 14.25622671  8.79147314
 16.00656115 15.78131807 12.44387399 16.52997278  8.78862902 13.13164118
 13.27554142 12.58133538 13.16966211]
