<a href="https://colab.research.google.com/github/gramelon2003/Python_ptdl/blob/master/Python_matrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Bài 1

In [ ]:
import numpy as np
a = np.random.randint(0, 20, size=(5,7))
print(a)

[[ 6  8  0 12 10 16 14]
 [14  9 14 19 11  5  5]
 [ 1  7 15 12  9  3  2]
 [18  9 19 15  7  5  7]
 [17  8  8  7  4 11 10]]


Bài 2

In [ ]:
import numpy as np
a = np.zeros((6, 7))
print(a)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


Bài 3

In [ ]:
import numpy as np
a = np.random.randint(0, 20, size=(7,7))
print(a)

[[ 2 16  7 12 16 14 13]
 [ 5  1 16  0  1 18  1]
 [13  5 15 10  6  9  8]
 [12  7 15 14 15  0 15]
 [ 2  0 16  1  6 10 14]
 [11  8 16 17  9  6  1]
 [ 2  8 19  5  7  6 15]]


Bài 4

In [ ]:
import numpy as np
a = np.zeros((6, 6))
np.fill_diagonal(a, 15)
print(a)

[[15.  0.  0.  0.  0.  0.]
 [ 0. 15.  0.  0.  0.  0.]
 [ 0.  0. 15.  0.  0.  0.]
 [ 0.  0.  0. 15.  0.  0.]
 [ 0.  0.  0.  0. 15.  0.]
 [ 0.  0.  0.  0.  0. 15.]]


Bài 5

In [ ]:
import numpy as np
a = np.random.randint(0, 20, size = (8, 8))
np.triu(a, 0)

array([[ 4, 13,  7, 14,  1,  5,  9, 12],
       [ 0,  2,  7,  2,  8,  5,  3,  8],
       [ 0,  0, 13,  5, 18, 17, 14, 19],
       [ 0,  0,  0, 17, 10,  4, 13,  3],
       [ 0,  0,  0,  0, 13, 11,  3,  2],
       [ 0,  0,  0,  0,  0,  7,  9, 11],
       [ 0,  0,  0,  0,  0,  0,  2,  8],
       [ 0,  0,  0,  0,  0,  0,  0,  5]])

Bài 6

In [ ]:
import numpy as np
a = np.random.randint(0, 20, size = (8, 8))
np.tril(a, 0)


array([[19,  0,  0,  0,  0,  0,  0,  0],
       [13,  5,  0,  0,  0,  0,  0,  0],
       [15, 14,  4,  0,  0,  0,  0,  0],
       [ 5, 19, 18, 16,  0,  0,  0,  0],
       [ 3, 14,  4,  5,  5,  0,  0,  0],
       [ 1,  8, 19, 16, 14, 19,  0,  0],
       [ 8, 11, 16,  2, 11, 10, 16,  0],
       [ 6,  8, 15,  2,  5,  4,  8, 11]])

Bài 7

In [ ]:
import numpy as np
a = np.identity(9)
print(a)

[[1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1.]]


Bài 8

8.1

In [ ]:
import numpy as np
a = np.random.randint(0, 20, size = (6, 7))
b = np.random.randint(0, 20, size = (6, 7))
c = a + b
print(a)
print(b)
print(c)

[[14 10  2 14  6 18 19]
 [13  9 16  5 10 18  8]
 [ 3  8 13  0  7 19 11]
 [ 4 17 13 19  9  5 11]
 [ 6 18 16  8 18 18 12]
 [ 4  5  8 16 19  9  7]]
[[ 6  6 18  1  5 12 14]
 [ 9 17 13  6  4  3 17]
 [19  6  7  7 11  6 11]
 [10 18 12 16  1  8  4]
 [ 0 13 15 13 19  9 10]
 [ 1  5  4  0  9 16  8]]
[[20 16 20 15 11 30 33]
 [22 26 29 11 14 21 25]
 [22 14 20  7 18 25 22]
 [14 35 25 35 10 13 15]
 [ 6 31 31 21 37 27 22]
 [ 5 10 12 16 28 25 15]]


8.2

In [ ]:
import numpy as np
c = int(input("nhap so n tu ban phim: "))
a = np.random.randint(0, 20, size = (5, 8))
d = a*c
print(a)
print(d)

nhap so n tu ban phim: 4
[[ 9  4 18 14 17  3 17  5]
 [15  7  0  4 18 16 13 17]
 [ 6  3 10  1  2 19 15  9]
 [12  4  6 12 15 10  7 11]
 [14  7  7  3 14 12 18  9]]
[[36 16 72 56 68 12 68 20]
 [60 28  0 16 72 64 52 68]
 [24 12 40  4  8 76 60 36]
 [48 16 24 48 60 40 28 44]
 [56 28 28 12 56 48 72 36]]


8.3

In [ ]:
import numpy as np
a = np.random.randint(0, 20, size = (3, 7))
b = np.transpose(a)
print(a)
print(b)

[[ 5  1  7 15 14  7 12]
 [13  6  6  7  3  3 11]
 [14 18  9 19 14  1 12]]
[[ 5 13 14]
 [ 1  6 18]
 [ 7  6  9]
 [15  7 19]
 [14  3 14]
 [ 7  3  1]
 [12 11 12]]


8.4

In [ ]:
import numpy as np
a = np.random.randint(0, 20, size = (5, 7))
b = np.random.randint(0, 20, size = (7, 3))
c = np.dot(a, b)
print(a)
print(b)
print(c)

[[10 14 16  1 16 17  3]
 [ 5 16  5  3  0 11  6]
 [15  6  1  8  3 12  0]
 [12 16 18 19 16 17  0]
 [ 5  8  8  1  5 18  3]]
[[13 19  2]
 [10 12  8]
 [ 3  6  4]
 [11 14 15]
 [ 8 10 12]
 [ 8 11  0]
 [ 3  5 12]]
[[ 602  830  439]
 [ 379  510  275]
 [ 466  637  238]
 [ 843 1141  701]
 [ 373  516  217]]


8.5

In [ ]:
import numpy as np
a = np.random.randint(0, 20, size = (5, 5))
b = np.linalg.inv(a)
print(a)
print(b)

[[17 14  9 11  7]
 [ 6 17  4 16 19]
 [13 17 10  3 11]
 [10 16  6  2  4]
 [17 11 18 19 13]]
[[ 0.17090342 -0.02752315  0.08092752 -0.15675203 -0.07204451]
 [-0.05613306  0.02079002 -0.06756757  0.15488565  0.00935551]
 [-0.15176715 -0.03638254 -0.00675676  0.1039501   0.10862786]
 [ 0.00959176  0.02969665 -0.12208231  0.06612644  0.03438622]
 [ 0.02012852  0.02537328  0.13912776 -0.16665092 -0.03744566]]


Bài 9

9.1

In [ ]:
import numpy as np
a = np.random.randint(0, 8, size = (1, 8))
print(a)

[[7 2 3 2 4 4 1 4]]


9.2

In [ ]:
import numpy as np
a = np.random.randint(0, 8, size = (8, 1))
print(a)

[[6]
 [0]
 [6]
 [7]
 [4]
 [3]
 [7]
 [1]]


Bài 10

In [ ]:
import numpy as np
m = int(input("nhap m: "))
n = int(input("nhap n: "))
if m != n:
    print ("ma tran khong kha nghich")
else:   
    a = np.random.randint(0, 20, size = (m, n))
    b = np.random.randint(0, 20, n)
    c = np.linalg.inv(a)
    x = c*b
    print(x)

nhap m: 4
nhap n: 4
[[ -4.1463964   -1.27702703   1.42567568   0.65878378]
 [ 20.25900901   9.18243243  -8.06081081  -1.16554054]
 [-22.13513514  -9.48648649   9.16216216   0.60810811]
 [ 14.93018018   5.89864865  -5.96621622  -0.18581081]]
